const constants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  IS_ALREADY_LOGGED_IN: "IS_ALREADY_LOGGED_IN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_RESET: "LOGIN_RESET",
  LOGOUT: "LOGOUT",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_ERROR: "SIGNUP_ERROR",
  SIGNUP_RESET: "SIGNUP_RESET",

  ORDERS_TODAY_REQUEST: "ORDERS_TODAY_REQUEST",
  ORDERS_TODAY_SUCCESS: "ORDERS_TODAY_SUCCESS",
  ORDERS_TODAY_ERROR: "ORDERS_TODAY_ERROR",

  SET_MANUAL_INPUT: "SET_MANUAL_INPUT",
  SALES_REQUEST: "SALES_REQUEST",
  SALES_SUCCESS: "SALES_SUCCESS",
  SALES_ERROR: "SALES_ERROR",

  CREATE_ORDER_REQUEST: "CREATE_ORDER_REQUEST",
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_ERROR: "CREATE_ORDER_ERROR",

  CREATE_ORDERS_REQUEST: "CREATE_ORDERS_REQUEST",
  CREATE_ORDERS_SUCCESS: "CREATE_ORDERS_SUCCESS",
  CREATE_ORDERS_ERROR: "CREATE_ORDERS_ERROR",
  ADD_LOCAL_ORDER: "ADD_LOCAL_ORDER",
  UPDATE_LOCAL_ORDER: "UPDATE_LOCAL_ORDER",
  REMOVE_LOCAL_ORDER: "REMOVE_LOCAL_ORDER",

  SEND_QUERY_REQUEST: "SEND_QUERY_REQUEST",
  SEND_QUERY_SUCCESS: "SEND_QUERY_SUCCESS",
  SEND_QUERY_ERROR: "SEND_QUERY_ERROR",
  UPDATE_FEE_QUERY: "UPDATE_FEE_QUERY",

  GET_ORDERS_REQUEST: "GET_ORDERS_REQUEST",
  GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",
  GET_ORDERS_ERROR: "GET_ORDERS_ERROR",

  GET_FEES_REQUEST: "GET_FEES_REQUEST",
  GET_FEES_SUCCESS: "GET_FEES_SUCCESS",
  GET_FEES_ERROR: "GET_FEES_ERROR",

  GET_CERTIFICATES_REQUEST: "GET_CERTIFICATES_REQUEST",
  GET_CERTIFICATES_SUCCESS: "GET_CERTIFICATES_SUCCESS",
  GET_CERTIFICATES_ERROR: "GET_CERTIFICATES_ERROR",

  IB_DATA_REQUEST: "IB_DATA_REQUEST",
  IB_DATA_SUCCESS: "IB_DATA_SUCCESS",
  IB_DATA_ERROR: "IB_DATA_ERROR",

  GET_DATA_IB_REQUEST: "GET_DATA_IB_REQUEST",
  GET_DATA_IB_SUCCESS: "GET_DATA_IB_SUCCESS",
  GET_DATA_IB_ERROR: "GET_DATA_IB_ERROR",

  OVERWRITE_REQUEST: "OVERWRITE_REQUEST",
  OVERWRITE_SUCCESS: "OVERWRITE_SUCCESS",
  OVERWRITE_ERROR: "OVERWRITE_ERROR",

  CANCEL_OVERWRITE_REQUEST:"  CANCEL_OVERWRITE_REQUEST",
  CANCEL_OVERWRITE_SUCCESS:"CANCEL_OVERWRITE_SUCCESS",
  CANCEL_OVERWRITE_ERROR:" CANCEL_OVERWRITE_ERROR",

  AUTO_PRICE_REQUEST: "AUTO_PRICE_REQUEST",
  AUTO_PRICE_SUCCESS: "AUTO_PRICE_SUCCESS",
  AUTO_PRICE_ERROR: "AUTO_PRICE_ERROR",

  LIST_NOTES_REQUEST: "LIST_NOTES_REQUEST",
  LIST_NOTES_SUCCESS: "LIST_NOTES_SUCCESS",
  LIST_NOTES_ERROR: "LIST_NOTES_ERROR",

  CREATE_NOTE_REQUEST: "CREATE_NOTE_REQUEST",
  CREATE_NOTE_SUCCESS: "CREATE_NOTE_SUCCESS",
  CREATE_NOTE_ERROR: "CREATE_NOTE_ERROR",

  DELETE_NOTE_REQUEST:" DELETE_NOTE_REQUEST",
  DELETE_NOTE_SUCCESS:" DELETE_NOTE_SUCCESS",
  DELETE_NOTE_ERROR:" DELETE_NOTE_ERROR",

  UPDATE_NEW_NOTE: "UPDATE_NEW_NOTE",
  RESET_NOTE: "RESET_NOTE",
  UPDATE_NOTE_REQUEST: "UPDATE_NOTE_REQUEST",
  UPDATE_NOTE_SUCCESS: "UPDATE_NOTE_SUCCESS",
  UPDATE_NOTE_ERROR: "UPDATE_NOTE_ERROR",

  CREATE_MARKET_REQUEST: "CREATE_MARKET_REQUEST",
  CREATE_MARKET_SUCCESS: "CREATE_MARKET_SUCCESS",
  CREATE_MARKET_ERROR: "CREATE_MARKET_ERROR",
  CREATE_MARKET_RESET: "CREATE_MARKET_RESET",

  MARKET_MAKER_REQUEST: "MARKET_MAKER_REQUEST",
  MARKET_MAKER_SUCCESS: "MARKET_MAKER_SUCCESS",
  MARKET_MAKER_ERROR: "MARKET_MAKER_ERROR",

  GET_GRAPH_DATA_REQUEST: "GET_GRAPH_DATA_REQUEST",
  GET_GRAPH_DATA_SUCCESS: "GET_GRAPH_DATA_SUCCESS",
  GET_GRAPH_DATA_ERROR: "GET_GRAPH_DATA_ERROR",
  GET_GRAPH_INDEX_REQUEST: "GET_GRAPH_INDEX_REQUEST",
  GET_GRAPH_INDEX_SUCCESS: "GET_GRAPH_INDEX_SUCCESS",
  GET_GRAPH_INDEX_ERROR: "GET_GRAPH_INDEX_ERROR",
  GRAPH_DATA_FOR_DAILY_CHANGE_REQUEST: "GRAPH_DATA_FOR_DAILY_CHANGE_REQUEST",
  GRAPH_DATA_FOR_DAILY_CHANGE_SUCCESS: "GRAPH_DATA_FOR_DAILY_CHANGE_SUCCESS",
  GRAPH_DATA_FOR_DAILY_CHANGE_ERROR: "GRAPH_DATA_FOR_DAILY_CHANGE_ERROR",

  CONFIRM_ORDER_REQUEST: "CONFIRM_ORDER_REQUEST",
  CONFIRM_ORDER_SUCCESS: "CONFIRM_ORDER_SUCCESS",
  CONFIRM_ORDER_ERROR: "CONFIRM_ORDER_ERROR",

  CONFIRM_SETTLEMENT_REQUEST: "CONFIRM_SETTLEMENT_REQUEST",
  CONFIRM_SETTLEMENT_SUCCESS: "CONFIRM_SETTLEMENT_SUCCESS",
  CONFIRM_SETTLEMENT_ERROR: "CONFIRM_SETTLEMENT_ERROR",

  UPDATE_CERTIFICATE_REQUEST: "UPDATE_CERTIFICATE_REQUEST",
  UPDATE_CERTIFICATE_SUCCESS: "UPDATE_CERTIFICATE_SUCCESS",
  UPDATE_CERTIFICATE_ERROR: "UPDATE_CERTIFICATE_ERROR",

  CIRDAN_FEE_REQUEST: "CIRDAN_FEE_REQUEST",
  CIRDAN_FEE_SUCCESS: "CIRDAN_FEE_SUCCESS",
  CIRDAN_FEE_ERROR: "CIRDAN_FEE_ERROR",
  UPDATE_LOCAL_FEE: "UPDATE_LOCAL_FEE",
  RESET_FEE: "RESET_FEE",

  UPDATE_CIRDAN_FEE_REQUEST: "UPDATE_CIRDAN_FEE_REQUEST",
  UPDATE_CIRDAN_FEE_SUCCESS: "UPDATE_CIRDAN_FEE_SUCCESS",
  UPDATE_CIRDAN_FEE_ERROR: "UPDATE_CIRDAN_FEE_ERROR",

  CREATE_CIRDAN_FEE_REQUEST: "CREATE_CIRDAN_FEE_REQUEST",
  CREATE_CIRDAN_FEE_SUCCESS: "CREATE_CIRDAN_FEE_SUCCESS",
  CREATE_CIRDAN_FEE_ERROR: "CREATE_CIRDAN_FEE_ERROR",

  UPDATE_USER_BID_REQUEST: "UPDATE_USER_BID_REQUEST",
  UPDATE_USER_BID_SUCCESS: "UPDATE_USER_BID_SUCCESS",
  UPDATE_USER_BID_ERROR: "UPDATE_USER_BID_ERROR",

  CLIENT_FEE_REQUEST: "CLIENT_FEE_REQUEST",
  CLIENT_FEE_SUCCESS: "CLIENT_FEE_SUCCESS",
  CLIENT_FEE_ERROR: "CLIENT_FEE_ERROR",

  CREATE_CLIENT_FEE_REQUEST: "CREATE_CLIENT_FEE_REQUEST",
  CREATE_CLIENT_FEE_SUCCESS: "CREATE_CLIENT_FEE_SUCCESS",
  CREATE_CLIENT_FEE_ERROR: "CREATE_CLIENT_FEE_ERROR",

  MONTH_SPLIT_REQUEST: "MONTH_SPLIT_REQUEST",
  MONTH_SPLIT_SUCCESS: "MONTH_SPLIT_SUCCESS",
  MONTH_SPLIT_ERROR: "MONTH_SPLIT_ERROR"
};

export default constants;
